---
version: 2.1
jobs:
  test:
    docker:
      - image: girder/girder_test:latest
      - image: mongo:4.4
        command: bash -c "mkdir /dev/shm/mongo && mongod --nojournal --dbpath=/dev/shm/mongo --noauth --bind_ip_all"

    steps:
      - checkout
      - run:
          name: Run server tests
          command: tox
      - run:
          name: Run web tests
          command: |
            npm install
            npm run lint
          working_directory: renalpath/web_client

workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
